version: "3.9"
services:
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports: 
            - "1433:1433"
        container_name: "Cleantracker-sqlserver"